Repository WildCodeSchool/orleans-0219-php-dionysos, pull requests merged in 2019-04, with the labels that each got.

#1 Initialisation du site avec mise en place de Bootstrap, appel de Twig…
  composer.lock
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/layout.html.twig
Labels: Corrections done

#2 renommage de layout.html.twig en base.html.twig, creation de layout v…
  src/View/Admin/layout-admin.html.twig
  src/View/Home/index.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Corrections done

#4 Merge de dev vers master.
  composer.lock
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Admin/layout-admin.html.twig
  src/View/Home/index.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#9 Sprint02 us08 structure footer
  composer.lock
  public/assets/css/style.css
  public/assets/images/Logo.png
  public/assets/images/cc-TR.png
  public/assets/images/cc-amex.png
  public/assets/images/cc-mastercard.png
  public/assets/images/cc-ticket-restau.png
  public/assets/images/cc-visa.png
  public/assets/images/facebook_logo.png
  public/assets/images/favicon.png
  public/assets/images/instagram_logo.png
  public/assets/images/tripadvisor_logo.png
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#23 Sprint 03 us 26 formulaire livre d or
  composer.lock
  public/assets/css/review.css
  src/Controller/ReviewController.php
  src/Model/ReviewManager.php
  src/View/Review/add.html.twig
  src/View/Review/index.html.twig
Labels: Corrections done, Reviewed by PO

#28 Dev
  composer.lock
  public/assets/css/review.css
  public/assets/css/style.css
  public/assets/images/Logo.png
  public/assets/images/cc-TR.png
  public/assets/images/cc-amex.png
  public/assets/images/cc-mastercard.png
  public/assets/images/cc-ticket-restau.png
  public/assets/images/cc-visa.png
  public/assets/images/facebook_logo.png
  public/assets/images/favicon.png
  public/assets/images/instagram_logo.png
  public/assets/images/tripadvisor_logo.png
  src/Controller/ReviewController.php
  src/Model/ReviewManager.php
  src/View/Review/add.html.twig
  src/View/Review/index.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#25 Sprint02 us02 navbar
  public/assets/css/style.css
  public/assets/images/bacchus2.png
  public/assets/images/vintage-concrete.png
  src/View/_header.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Corrections done, Reviewed by PO

#30 Modification du footer
  public/assets/css/style.css
  src/View/layout-visitor.html.twig
Labels: Corrections done, Reviewed by PO

#31 Sprint 03 us 03 jumbotron
  public/assets/css/style.css
  public/assets/images/arrow-down.png
  public/assets/images/jumbotron_1.jpg
  src/View/Home/index.html.twig
  src/View/_jumbotron.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Corrections done, PO needs a vacation

#42 Sprint 03 us 32 aboutus
  composer.json
  composer.lock
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/_about-us.html.twig
Labels: Reviewed by PO

#44 US_27_cards livre d'or
  public/assets/css/review.css
  src/Controller/ReviewController.php
  src/View/Review/add.html.twig
  src/View/Review/index.html.twig
Labels: Reviewed by PO

#45 Sprint 04 us 06 reservationhome
  public/assets/css/style.css
  public/assets/images/resa.jpg
  src/View/Home/index.html.twig
  src/View/_reservation-home.html.twig
Labels: Reviewed by PO

#46 Sprint 04 us 07 noustrouverhome
  public/assets/css/admin-style.css
  public/assets/css/style.css
  public/assets/images/plan.png
  src/View/Home/index.html.twig
  src/View/_noustrouverhome.html.twig
Labels: Reviewed by PO

#43 Sprint 04 us 05 menuhome
  public/assets/css/style.css
  public/assets/images/menu.webp
  src/View/Home/index.html.twig
  src/View/_home-menu.html.twig
Labels: Reviewed by PO

#48 merge dev to master
  composer.json
  composer.lock
  public/assets/css/admin-style.css
  public/assets/css/review.css
  public/assets/css/style.css
  public/assets/images/arrow-down.png
  public/assets/images/bacchus2.png
  public/assets/images/jumbotron_1.jpg
  public/assets/images/menu.webp
  public/assets/images/plan.png
  public/assets/images/resa.jpg
  public/assets/images/vintage-concrete.png
  src/Controller/AdminController.php
  src/Controller/ReviewController.php
  src/View/Admin/index.html.twig
  src/View/Admin/layout-admin.html.twig
  src/View/Home/index.html.twig
  src/View/Review/add.html.twig
  src/View/Review/index.html.twig
  src/View/_about-us.html.twig
  src/View/_header.html.twig
  src/View/_home-menu.html.twig
  src/View/_jumbotron.html.twig
  src/View/_noustrouverhome.html.twig
  src/View/_reservation-home.html.twig
  src/View/base.html.twig
  src/View/layout-admin.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#50 Us fix design
  public/assets/css/review.css
  public/assets/css/style.css
  public/assets/images/bacchus2.png
  public/assets/images/exclusive_paper.png
  public/assets/images/vintage-concrete.png
  src/View/Home/index.html.twig
  src/View/_about-us.html.twig
  src/View/_find-us-home.html.twig
  src/View/_header.html.twig
  src/View/_home-menu.html.twig
  src/View/_noustrouverhome.html.twig
  src/View/_reservation-home.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#55 Dev to master
  public/assets/css/review.css
  public/assets/css/style.css
  public/assets/images/bacchus2.png
  public/assets/images/exclusive_paper.png
  public/assets/images/vintage-concrete.png
  src/View/Home/index.html.twig
  src/View/_about-us.html.twig
  src/View/_find-us-home.html.twig
  src/View/_header.html.twig
  src/View/_home-menu.html.twig
  src/View/_noustrouverhome.html.twig
  src/View/_reservation-home.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#52 Sprint 04 us 22 findus
  src/Controller/FindUsController.php
  src/View/Findus/index.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#53 jointure cards et formulaire
  public/assets/css/review.css
  src/Controller/ReviewController.php
  src/View/Review/add.html.twig
  src/View/Review/index.html.twig
Labels: Reviewed by PO

#56 Dev to master
  public/assets/css/review.css
  src/Controller/FindUsController.php
  src/Controller/ReviewController.php
  src/View/Findus/index.html.twig
  src/View/Home/index.html.twig
  src/View/Review/add.html.twig
  src/View/Review/index.html.twig
Labels: Reviewed by PO

#62 correction graphique page nous trouver
  public/assets/css/style.css
  public/assets/images/puce.png
  src/View/Findus/index.html.twig
Labels: Reviewed by PO

#69 Dev
  public/assets/css/review.css
  public/assets/css/style.css
  public/assets/images/puce.png
  src/Controller/ReviewController.php
  src/Model/ReviewManager.php
  src/View/Findus/index.html.twig
  src/View/Review/add.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#49 Sprint04 us25 page menu
  public/assets/css/style.css
  public/assets/images/faitmaison.png
  src/Controller/DishController.php
  src/Model/CategoryManager.php
  src/Model/DishManager.php
  src/Model/MenuManager.php
  src/View/Dish/index.html.twig
Labels: Corrections done, Reviewed by PO

#64 Us fix design
  public/assets/css/style.css
  public/assets/images/dishes.jpg
  public/assets/images/jeanne-arc-martroi.jpg
  public/assets/images/restaurant_image.jpg
  src/View/_find-us-home.html.twig
  src/View/_header.html.twig
  src/View/_home-menu.html.twig
  src/View/_jumbotron.html.twig
  src/View/_reservation-home.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Conflict solved, Reviewed by PO

#68 Sprint 04 us 15 admin livre d or
  public/assets/css/admin-style.css
  src/Controller/AdminReviewController.php
  src/Model/AdminReviewManager.php
  src/Model/ReviewManager.php
  src/View/Admin/review.html.twig
  src/View/base.html.twig
  src/View/layout-admin.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#51 Sprint03 us24 structure reservation
  .gitignore
  public/assets/css/style.css
  public/assets/images/call-icon.png
  src/Controller/ReservationController.php
  src/Model/ReservationManager.php
  src/View/Reservation/add.html.twig
  src/View/Reservation/index.html.twig
  src/View/Reservation/success.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#79 Dev
  .gitignore
  public/assets/css/admin-style.css
  public/assets/css/style.css
  public/assets/images/call-icon.png
  public/assets/images/dishes.jpg
  public/assets/images/faitmaison.png
  public/assets/images/jeanne-arc-martroi.jpg
  public/assets/images/restaurant_image.jpg
  src/Controller/AdminReviewController.php
  src/Controller/DishController.php
  src/Controller/ReservationController.php
  src/Model/AdminReviewManager.php
  src/Model/CategoryManager.php
  src/Model/DishManager.php
  src/Model/MenuManager.php
  src/Model/ReservationManager.php
  src/Model/ReviewManager.php
  src/View/Admin/review.html.twig
  src/View/Dish/index.html.twig
  src/View/Reservation/add.html.twig
  src/View/Reservation/index.html.twig
  src/View/Reservation/success.html.twig
  src/View/_find-us-home.html.twig
  src/View/_header.html.twig
  src/View/_home-menu.html.twig
  src/View/_jumbotron.html.twig
  src/View/_reservation-home.html.twig
  src/View/base.html.twig
  src/View/layout-admin.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#80 Sprint05 US13 - admin ajout des plats
  src/Controller/AdminDishController.php
  src/Model/AdminDishManager.php
  src/View/Admin/Dish/_form.html.twig
  src/View/Admin/Dish/add.html.twig
Labels: Corrections done, Reviewed by PO

#82 list category drink in admin
  src/Controller/AdminDrinkCategoryController.php
  src/Model/DrinkCategoryManager.php
  src/View/AdminDrinkCategory/index.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by PO

#83 Sprint04 us34 page photo
  public/assets/css/style.css
  public/assets/images/photo1.jpg
  public/assets/images/photo10.jpg
  public/assets/images/photo100.jpg
  public/assets/images/photo101.jpg
  public/assets/images/photo102.jpg
  public/assets/images/photo103.jpg
  public/assets/images/photo104.jpg
  public/assets/images/photo105.jpg
  public/assets/images/photo106.jpg
  public/assets/images/photo107.jpg
  public/assets/images/photo108.jpg
  public/assets/images/photo15.jpg
  public/assets/images/photo16.jpg
  public/assets/images/photo17.jpg
  public/assets/images/photo18.jpg
  public/assets/images/photo3.jpg
  public/assets/images/photo5.jpg
  public/assets/images/photo7.jpg
  public/assets/images/photo9.jpg
  src/Controller/GalleryController.php
  src/View/Gallery/index.html.twig
  src/View/_header.html.twig
Labels: Reviewed by PO

#85 Sprint05 fix jumbotron buttons style
  .gitignore
  public/assets/css/style.css
  src/View/Admin/index.html.twig
  src/View/Reservation/add.html.twig
  src/View/_jumbotron.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Conflict solved, Reviewed by PO

#84 Sprint 05 us 41 admin categories
  public/assets/css/admin-style.css
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/Dish/category.html.twig
  src/View/Dish/index.html.twig
  src/View/base.html.twig
Labels: Corrections done, Reviewed by PO

#91 add drink categ
  public/assets/css/admin-style.css
  src/Controller/AdminDrinkCategoryController.php
  src/Model/DrinkCategoryManager.php
  src/View/AdminDrinkCategory/_form.html.twig
  src/View/AdminDrinkCategory/add.html.twig
  src/View/AdminDrinkCategory/index.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#94 Lister et supprimer les plats de la carte
  src/Controller/AdminDishController.php
  src/Model/AdminDishManager.php
  src/Model/DishManager.php
  src/View/Admin/Dish/index.html.twig
  src/View/Admin/Dish/show.html.twig
Labels: Corrections done, for PO to validate
