Repository WildCodeSchool/orleans-0219-php-dionysos, pull requests merged in 2019-05, with the labels that each got.

#95 edit categ drink
  src/Controller/AdminDrinkCategoryController.php
  src/View/AdminDrinkCategory/_form.html.twig
  src/View/AdminDrinkCategory/edit.html.twig
  src/View/AdminDrinkCategory/index.html.twig
Labels: Reviewed by PO

#96 delete categ drink
  src/Controller/AdminDrinkCategoryController.php
  src/View/AdminDrinkCategory/index.html.twig
Labels: for PO to validate

#93 Us fix livre d or
  public/assets/css/style.css
  src/Controller/ReviewController.php
  src/Model/ReviewManager.php
  src/View/Review/add.html.twig
  src/View/_review-cards.html.twig
Labels: Reviewed by PO

#100 list drinks admin
  src/Controller/AdminDrinkController.php
  src/Model/DrinkManager.php
  src/View/AdminDrink/index.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by PO

#102 Sprint 05 us 52 ajout categories
  public/assets/css/admin-style.css
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/Admin/Dish/add_category.html.twig
  src/View/Admin/Dish/category.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by PO

#104 add drink admin
  src/Controller/AdminDrinkController.php
  src/Model/DrinkManager.php
  src/View/AdminDrink/_form.html.twig
  src/View/AdminDrink/add.html.twig
Labels: Reviewed by PO

#70 US_40 Afficher la carte des vins
  public/assets/css/style.css
  public/assets/images/organic_logo.jpg
  src/Controller/DishController.php
  src/Model/DrinkManager.php
  src/Model/WineManager.php
  src/Model/WineTypeManager.php
  src/View/Dish/index.html.twig
  src/View/Wine/index.html.twig
Labels: Reviewed by PO

#105 Supprimer des plats
  public/assets/css/admin-style.css
  src/View/Admin/Dish/show.html.twig
Labels: Reviewed by PO

#106 Sprint03 us24 structure reservation
  src/Controller/ReservationController.php
  src/View/Reservation/success.html.twig
Labels: Reviewed by PO

#74 Sprint 04 us 37 accueil cards review
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/HomeReviewManager.php
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#108 Sprint04 us25 page menu
  public/assets/css/style.css
  public/assets/images/drinks.jpg
  public/assets/images/page-menu.jpg
  src/View/Dish/index.html.twig
  src/View/_jumbotron.html.twig
Labels: Reviewed by PO

#109 Corrections pour validator W3C
  src/View/_find-us-home.html.twig
  src/View/_home-menu.html.twig
  src/View/_jumbotron.html.twig
  src/View/_reservation-home.html.twig
  src/View/base.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO

#110 Corrections liens et style: admin dish
  public/assets/css/admin-style.css
  src/View/Admin/Dish/index.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by PO

#111 Sprint 05 us fix design
  public/assets/css/style.css
  public/assets/images/cathedrale-orleans.jpg
  src/Controller/ReviewController.php
  src/View/Findus/index.html.twig
  src/View/Gallery/index.html.twig
  src/View/Home/index.html.twig
  src/View/Review/add.html.twig
  src/View/_about-us.html.twig
  src/View/_find-us-home.html.twig
  src/View/_jumbotron.html.twig
  src/View/_reservation-home.html.twig
Labels: Reviewed by PO

#112 Fix - Afficher plats
  public/assets/css/style.css
  src/View/Dish/index.html.twig
Labels: Reviewed by PO

#113 ajout jumbotrons
  public/assets/css/style.css
  public/assets/images/guest-book.jpg
  public/assets/images/reservation.jpg
  src/View/Reservation/add.html.twig
  src/View/Review/add.html.twig
Labels: Reviewed by PO

#114 fix menu - carte des boissons sur la droite
  src/View/Dish/index.html.twig
Labels: Reviewed by PO

#115 Dev
  composer.json
  composer.lock
  config/db.php.dist
  public/assets/css/admin-style.css
  public/assets/css/style.css
  public/assets/images/cathedrale-orleans.jpg
  public/assets/images/drinks.jpg
  public/assets/images/guest-book.jpg
  public/assets/images/organic_logo.jpg
  public/assets/images/page-menu.jpg
  public/assets/images/reservation.jpg
  src/Controller/AdminReservationController.php
  src/Controller/DishController.php
  src/Controller/HomeController.php
  src/Controller/ReservationController.php
  src/Controller/ReviewController.php
  src/Model/AdminReservationManager.php
  src/Model/DrinkManager.php
  src/Model/HomeReviewManager.php
  src/Model/WineManager.php
  src/Model/WineTypeManager.php
  src/View/Admin/Dish/index.html.twig
  src/View/Admin/Dish/show.html.twig
  src/View/AdminReservation/index.html.twig
  src/View/Dish/index.html.twig
  src/View/Email/reservation.html.twig
  src/View/Findus/index.html.twig
  src/View/Gallery/index.html.twig
  src/View/Home/index.html.twig
  src/View/Reservation/add.html.twig
  src/View/Reservation/success.html.twig
  src/View/Review/add.html.twig
  src/View/Wine/index.html.twig
  src/View/_about-us.html.twig
  src/View/_find-us-home.html.twig
  src/View/_home-menu.html.twig
  src/View/_jumbotron.html.twig
  src/View/_reservation-home.html.twig
  src/View/base.html.twig
  src/View/layout-admin.html.twig
  src/View/layout-visitor.html.twig
Labels: Reviewed by PO
